"""add meeting_url to time_slots

Revision ID: 4598f62e3443
Revises: cdb10d2177c8
Create Date: 2025-07-11 09:19:17.475732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4598f62e3443'
down_revision = 'cdb10d2177c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('meeting_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_slots', 'meeting_url')
    # ### end Alembic commands ###
