"""add slug and password_hash to student, password_hash to teacher

Revision ID: 9f6b68670c83
Revises: 4598f62e3443
Create Date: 2025-07-17 11:05:49.652290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6b68670c83'
down_revision = '4598f62e3443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('slug', sa.String(length=20), unique=True, nullable=True))
    op.add_column('students', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('teachers', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'password_hash')
    op.drop_column('students', 'password_hash')
    op.drop_column('students', 'slug')
    # ### end Alembic commands ###
