"""Initial migration

Revision ID: cdb10d2177c8
Revises: 
Create Date: 2025-07-08 10:04:52.018708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb10d2177c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=20), unique=True, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=False), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=False), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('current_bookings', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', 'CANCELLED', name='slotstatus'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_slots_end_time'), 'time_slots', ['end_time'], unique=False)
    op.create_index(op.f('ix_time_slots_start_time'), 'time_slots', ['start_time'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('student_notes', sa.String(), nullable=True),
    sa.Column('teacher_notes', sa.String(), nullable=True),
    sa.Column('booking_time', sa.DateTime(timezone=False), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=False), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_time'), 'bookings', ['booking_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_booking_time'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_time_slots_start_time'), table_name='time_slots')
    op.drop_index(op.f('ix_time_slots_end_time'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
